### ISSUE TITLE
problem factories fixed size initial dataset - RFP and GFP

### ISSUE THREAD

**Issue by RMichae1** [MachineLearningLifeScience/poli#132]
For experiments we require the problem factory to return an initial dataset of a fixed size, ie. I want to use the factory `create` method to return a `x_0, y_0` of a specific size.

Until now the factory create was invoked and the resulting initial dataset was subselected, however during loading the black-box function was then called more times than initial observations available. This is misleading in the tracking.

**Comment by RMichae1** [comment]
For the RFP FoldX Stability and SASA case we require minimum the number of sequences in the Pareto front.
Hardcode the IDs of these sequences.

**Comment by miguelgondu** [comment]
Since `foldx_stability_and_sasa` should be generic (and not really specific to the `rfp` problem of lambo), I think we should move this hard-coding to the experiments themselves, right?

I'm happy to wait on this until after we're done with our current project.

**Comment by RMichae1** [comment]
This is true!  `foldx_stability_and_sasa` should not include the Pareto front!
I'll make a dedicated `rfp_foldx_stability_and_sasa` which includes the Pareto front definition explicitly.
The original `foldx_stability_and_sasa` will be reverted to the version without number of sequences and hard-coded PDB files.

**Comment by RMichae1** [comment]
Does #139 fix this issue to our satisfaction?
