### ISSUE TITLE
Custom function API addition

### ISSUE THREAD

**Issue by RMichae1** [MachineLearningLifeScience/poli#160]
Currently we do not provide capabilities to load a custom user-defined function with poli.

We require the user to add any function as an objective to the objective repository.
However that may be a large hurdle for initial users of the poli library.

We could consider adding an empty black-box objective/ dummy objective on any available data assets and let the user specify a custom function for f.

This way benchmarking and dev can be done quicker if a callable function object is available for the user without the requirement to make substantial contributions to poli.

**Comment by miguelgondu** [comment]
I like it, were you imagining something like this?:

```python
from poli.objective_repository import DummyBlackBox

f = DummyBlackBox(black_box=lambda x: 0.0)

# then f(whatever) == 0.0, and the logging and other functionalities of black boxes can still be attached and measured? 
```

**Comment by RMichae1** [comment]
Exactly like that. +1

**Comment by miguelgondu** [comment]
to preserve shapes, we would need something like `lambda x: np.zeros(len(x)).reshape(1, -1)`, but these are minor details.

**Comment by miguelgondu** [comment]
We could implement a `lambda` black box registration for isolation.

The way to do it would be by asking the user to implement a subclass of `AbstractIsolatedFunction`.

**Comment by miguelgondu** [comment]
I decided to go for something simpler, like I originally proposed.

Now you can do something like

```python
import numpy as np

from poli.core.black_box_information import BlackBoxInformation
from poli.core.lambda_black_box import LambdaBlackBox
from poli.tests.observers.test_observers import SimpleObserver


def example():
    def f_(x: np.ndarray) -> np.ndarray:
        return np.zeros((len(x), 1))

    f = LambdaBlackBox(
        function=f_,
    )

    ...
```

We can also pass a custom information object.
