### ISSUE TITLE
What happens if you don't specify an `observer_name`?

### ISSUE THREAD

**Issue by miguelgondu** [MachineLearningLifeScience/poli#179]
Decide on whether to
1. do nothing if the user doesn't provide an observer name.
2. Provide a default observer that does nothing.

In other words, do we expect the attribute `f.observer` from black boxes to always be populated?

**Comment by miguelgondu** [comment]
Hi @SimonBartels, Has this issue been addressed? Feel free to close it if it has.

**Comment by SimonBartels** [comment]
In the current implementation the default observer is instantiated. If the user did not specify one, this is the object `DefaultObserver` which does nothing.
