### ISSUE TITLE
Should we add CALVADOS?

### ISSUE THREAD

**Issue by miguelgondu** [MachineLearningLifeScience/poli#206]
https://github.com/KULL-Centre/CALVADOS/tree/main

**Comment by miguelgondu** [comment]
The pipeline also includes some interesting other properties (e.g. energies).

**Comment by miguelgondu** [comment]
Updated version: https://github.com/KULL-Centre/_2024_Cao_CALVADOSCOM

**Comment by miguelgondu** [comment]
Hey Simon, should we close this issue? (Maybe after adding a comment with our conclusions on whether CALVADOS makes sense to add)

**Comment by SimonBartels** [comment]
Yes, I agree. For now there is no meaningful objective that we can optimize with CALVADOS.
