### ISSUE TITLE
The external process is not terminating gracefully

### ISSUE THREAD

**Issue by miguelgondu** [MachineLearningLifeScience/poli#21]
At some point, the call to `terminate` in the `ExternalBlackBox` started to throw a weird exception:

```
Exception ignored in: <function AbstractBlackBox.__del__ at 0x11ec181f0>
Traceback (most recent call last):
  File "/Users/myuser/Projects/poli/src/poli/core/abstract_black_box.py", line 80, in __del__
  File "/Users/myuser/Projects/poli/src/poli/objective_factory.py", line 60, in terminate
  File "/Users/myuser/Projects/poli/src/poli/core/util/inter_process_communication/process_wrapper.py", line 64, in send
  File "/Users/myuser/anaconda3/envs/poli-dev/lib/python3.9/multiprocessing/connection.py", line 206, in send
AttributeError: 'NoneType' object has no attribute 'dumps'
```

When I check `connection.py` in multiprocessing, this is the line it refers to:

```python
def send(self, obj):
    """Send a (picklable) object"""
    self._check_closed()
    self._check_writable()
    self._send_bytes(_ForkingPickler.dumps(obj))  # <--- this line
```

For some reason, the `_ForkingPickler` becomes `None`.

To replicate, run the `our_aloha` example in `examples/a_simple_objective_function_registration`.

**Comment by miguelgondu** [comment]
The process terminates gracefully if we add an `f.terminate()`. Weird! The `ExternalBlackBox` should be doing this at `__del__` time.

**Comment by miguelgondu** [comment]
Interesting, the `__del__` for the external black box might be called too late.

[This is what the python documentation says:](https://docs.python.org/3/reference/datamodel.html#object.__del__) 

![Screenshot 2023-09-01 at 19 48 52](https://github.com/MachineLearningLifeScience/poli/assets/8268159/2770936a-bcc7-4324-9a2d-ea872f081734)

**Comment by miguelgondu** [comment]
Would love some input or help on this @RMichae1, @SimonBartels. @MachineLearningLifeScience/discrete-sequence-optimization.

**Comment by miguelgondu** [comment]
One very naïve way to solve this would be to add a try-except in the `AbstractBlackBox`'s deletion, no?

**Comment by RMichae1** [comment]
Wouldn't that try-except go into the factory terminate?
I'm not sure how the try-except gets called _inside_ a `__del__`

**Comment by RMichae1** [comment]
Yes. Wrapping the `dumps` call.

**Comment by miguelgondu** [comment]
I think we should wrap the `ExternalBlackBox`'s `terminate` instead. I'm on it.
