### ISSUE TITLE
Inconsistent Problem Registration and Isolation Management

### ISSUE THREAD

**Issue by SimonBartels** [MachineLearningLifeScience/poli#211]
At the moment there are two functions to register problems: `register_isolated_function` and `register_problem`.
I suggest to rename `register_isolated_function` to `register_problem` and to remove the latter.
Further, the isolation mechanism is fairly generic: try import and isolate on failure. We should move this part to the `AbstractProblemFactory`.

**Comment by SimonBartels** [comment]
I just discovered that there is also `register_problem_from_repository`.

**Comment by miguelgondu** [comment]
So far, we have three different isolation mechanisms:
1. `register_problem`,
2. `register_isolated_function`, and 
3. `register_problem_from_repository`.

We only need one, and I'm tilting towards 2. Isolated functions are the only thing that needs isolation after the API change.

**Comment by miguelgondu** [comment]
Next steps:

- Cleaning up `register_problem` and `register_problem_from_repository`.
- Cleaning up `isolation` inside `util`. Several of these will not be used. Keep in mind that `observer`s might use one of these.
- Unify isolation for `isolated_function`s and for `observer`s (i.e. having a single `dynamically_instantiate` function for all of them).

**Comment by miguelgondu** [comment]
Also keep in mind #176 .

**Comment by SimonBartels** [comment]
Furthermore there are the modules
* `external_isolated_function_script`
* `external_problem_factory_script`

Note: `observer_wrapper` uses `dynamically_instantiate` in the latter module.
