### ISSUE TITLE
Add foldx_gfp_lambo

### ISSUE THREAD

**Issue by RMichae1** [MachineLearningLifeScience/poli#37]
To run GFP experiments we require:

- [ ] a GFPWrapper
- [ ] a GFPWrapperFactory
- [ ] a hydra config for Lambo instantiation
- [ ] problem registration
- [ ] addition to objective_repository __init__
- [ ] addition to the documentation

test iterations on lambo experiments

**Comment by miguelgondu** [comment]
Hi Richard, you recently added this one, right?

**Comment by RMichae1** [comment]
Mixing GFP and Lambo is no longer a requirement, and somewhat a nonsense request on my end. Closing this one.
